###
# data sources
data_sources:
    sname: &sname
      placeholder-sname
    run_dir: .
    nb_path_root: .

###
# computation config keys
computation_config:
    default_kernel_name: mom6-tools-nbscuid


###
# computational notebooks
compute_notebooks:
  
  index:
    parameter_groups:
      none:
        sname: *sname

  Equatorial_comparison:
    parameter_groups:
      none:
        sname: *sname
        
  ocean_stats:
    parameter_groups:
      none:
        sname: *sname

  poleward_heat_transport:
  ### type error in plot
    parameter_groups:
      none:
        sname: *sname     

  section_transports:
    parameter_groups:
      none:
        sname: *sname

  surface:
    parameter_groups:
      none:
        sname: *sname

  TS_drift:
    parameter_groups:
      none:
        sname: *sname

  TS_levels:
    parameter_groups:
      none:
        sname: *sname  

  meridional_overturning:
    parameter_groups:
      none:
        sname: *sname

  velocity_levels:
    parameter_groups:
      none:
        sname: *sname

##############################


#  EquatorialOceanMetrics:
#    parameter_groups:
#      none:
#        sname: *sname

#  forcing:
#    parameter_groups:
#      none:
#        sname: *sname

#  globally_averaged_ocean_properties:
#    parameter_groups:
#      none:
#        sname: *sname

#  region_masks:
#    parameter_groups:
#      none:
#        sname: *sname

#  seaice:
#    parameter_groups:
#      none:
#        sname: *sname

#  close_tracer_budgets:
#    parameter_groups:
#      none:
#        sname: *sname

#  combining-tiles:
#    parameter_groups:
#      none:
#        sname: *sname

#  diags_case:
#    parameter_groups:
#      none:
#        sname: *sname





###
# book table of contents
book_toc:
  format: jb-book
  root: index
  parts:
    - caption: mom6-tools example notebooks
      chapters:

        - file: Equatorial_comparison
        - file: ocean_stats
        - file: poleward_heat_transport
        - file: section_transports
        - file: surface
        - file: TS_drift
        - file: TS_levels
        - file: meridional_overturning       
        - file: velocity_levels
    
###################################################
        # - file: EquatorialOceanMetrics
        # - file: forcing
        # - file: globally_averaged_ocean_properties
        # - file: region_masks
        # - file: seaice
        # - file: close_tracer_budgets
        # - file: combining-tiles
        # - file: diags_case

###
# book _config.yml keys
book_config_keys:
  title: mom6_solutions automation
  repository:
    url: https://github.com/rmshkv/nbscuid
    path_to_book: notebooks
    branch: main